name: Noctis
version: ${project.version}
main: ca.anmolbrar.Noctis
api-version: 1.13
authors: [Anmol Brar]
website: anmolbrar.ca

commands:
  markers:
    description: Markers Command
  cobble:
    description: Cobble Command
  graves:
    description: Graves Command
  pin:
    description: Pin Command
  ores:
    description: Ores Command
  protection:
    description: Protection Command
    permission: protection.command
  nickname:
    description: Nickname Command
  sets:
    description: Sets Command
  coords:
    description: Coords Command